In [36]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
import numpy as np
iris=load_iris()
import warnings
warnings.filterwarnings('ignore')

In [37]:
lr= cross_val_score(LogisticRegression(),iris.data,iris.target)
lr

array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [38]:
rf =cross_val_score(RandomForestClassifier(),iris.data,iris.target)
rf

array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ])

In [39]:
sv =cross_val_score(SVC(),iris.data,iris.target)
sv

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [40]:
dt= cross_val_score(DecisionTreeClassifier(),iris.data,iris.target)
dt

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])

In [41]:
np.average(lr)             #Logistic Regression

0.9733333333333334

In [42]:
np.average(rf)            #Random Forest

0.96

In [43]:
np.average(sv)             #Support Vector

0.9666666666666666

In [44]:
np.average(dt)             #Decision Tree

0.9600000000000002

In [46]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [53]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

scores_logistic = []
scores_svm = []
scores_rf = []
scores_dt= []

for train_index, test_index in folds.split(iris.data, iris.target):
    X_train, X_test, y_train, y_test = iris.data[train_index], iris.data[test_index], \
                                       iris.target[train_index], iris.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test))
    scores_dt.append(get_score(DecisionTreeClassifier(), X_train, X_test, y_train, y_test))

In [54]:
np.average(scores_logistic)

0.9733333333333333

In [55]:
np.average(scores_svm)

0.96

In [56]:
np.average(scores_rf)

0.96

In [57]:
np.average(scores_dt)

0.9533333333333333

# The model with best performance is Logistic Regression in this case.