In [36]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
import numpy as np
iris=load_iris()
import warnings
warnings.filterwarnings('ignore')

In [37]:
lr= cross_val_score(LogisticRegression(),iris.data,iris.target)
lr

array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [38]:
rf =cross_val_score(RandomForestClassifier(),iris.data,iris.target)
rf

array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ])

In [39]:
sv =cross_val_score(SVC(),iris.data,iris.target)
sv

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [40]:
dt= cross_val_score(DecisionTreeClassifier(),iris.data,iris.target)
dt

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])

In [41]:
np.average(lr)             #Logistic Regression

0.9733333333333334

In [42]:
np.average(rf)            #Random Forest

0.96

In [43]:
np.average(sv)             #Support Vector

0.9666666666666666

In [44]:
np.average(dt)             #Decision Tree

0.9600000000000002

The highest validation score was for Logistic Regression in this case for iris data set.